In [85]:
import torch
import random
import numpy as np

In [86]:
random.seed(10)
features = 4
alpha = 0.1

X = np.random.rand(100, features)
X = torch.from_numpy(X)

W_real = torch.randn(features, 1, dtype=torch.float64)
B_real = torch.ones(1) * random.randrange(10)

Y = torch.matmul( X, W_real) + B_real
Y.shape, B_real.shape, X.shape

(torch.Size([100, 1]), torch.Size([1]), torch.Size([100, 4]))

In [92]:
def forward(w, x, b):
    return torch.matmul(x, w) + b

def loss(prediction, labels):
    return torch.mean((prediction - labels) ** 2)

weights = torch.randn(features, 1, requires_grad=True, dtype=torch.float64)
bias = torch.randn(1, requires_grad=True, dtype=torch.float64)

for _ in range(10000):
    pred = forward(weights, X, bias)
    l = loss(pred, Y)

    l.backward()

    with torch.no_grad():
        weights.data -= weights.grad.data * alpha  
        bias.data -= bias.grad.data * alpha  

    weights.grad.zero_()
    bias.grad.zero_()

    print("loss", l.item())

loss 118.82404002880696
loss 42.80473133491955
loss 16.240632798781196
loss 6.939803400290775
loss 3.665521715970934
loss 2.4955521009011803
loss 2.0608038316349346
loss 1.8833701517685983
loss 1.796415573225869
loss 1.7416856978738042
loss 1.6988273625834303
loss 1.6607175910930843
loss 1.6248520647363094
loss 1.5903392193192467
loss 1.5568510041482586
loss 1.5242566208743664
loss 1.4924946593212738
loss 1.4615284472400552
loss 1.4313304468322932
loss 1.4018767907999785
loss 1.3731453582657074
loss 1.3451150869087518
loss 1.3177657171964432
loss 1.291077688008142
loss 1.265032085650542
loss 1.23961061203637
loss 1.2147955600595588
loss 1.1905697919710208
loss 1.1669167192723422
loss 1.1438202835924478
loss 1.1212649383437552
loss 1.0992356310706684
loss 1.0777177864444654
loss 1.0566972898736018
loss 1.0361604717042503
loss 1.0160940919884245
loss 0.9964853257984875
loss 0.9773217490678049
loss 0.9585913249381401
loss 0.9402823905951465
loss 0.9223836445740075
loss 0.9048841345179519


In [93]:
W_real, weights, B_real, bias

(tensor([[ 1.5228],
         [ 0.7770],
         [-0.0905],
         [ 0.2699]], dtype=torch.float64),
 tensor([[ 1.5228],
         [ 0.7770],
         [-0.0905],
         [ 0.2699]], dtype=torch.float64, requires_grad=True),
 tensor([9.]),
 tensor([9.0000], dtype=torch.float64, requires_grad=True))